In [1]:
import evaluate
import Utils
import network

import numpy as np

In [10]:
image_num = 180
model = network.Conv64Features()
model.to('cpu').eval()
D = 50

In [11]:
# dohvati slike
left = Utils.get_left_image(image_num)
right = Utils.get_right_image(image_num)

In [12]:
# pretvori slike za ulaz u model
left_model_input = evaluate.transform_image_for_model(left)
right_model_input = evaluate.transform_image_for_model(right)

In [13]:
# provuci slike kroz model i pretvori ih u prikladni ndarray
left_output = evaluate.transform_model_output_to_ndarray(model(left_model_input))
right_output = evaluate.transform_model_output_to_ndarray(model(right_model_input))

In [14]:
similarities_at_all_D_disparities = np.stack([evaluate.similarity_at_d(left_output, right_output, d) for d in range(D)], axis=2)

In [15]:
similarity_at_1 = evaluate.similarity_at_d(left_output, right_output, 1)

In [16]:
similarities_at_all_D_disparities.shape

(376, 1241, 50)

In [17]:
np.argmin(similarities_at_all_D_disparities, axis=2)

array([[ 1,  2,  3, ...,  2,  3,  4],
       [ 1,  2,  3, ...,  2,  3,  3],
       [ 1,  2,  3, ...,  2,  3,  3],
       ...,
       [ 1,  2,  3, ..., 30, 31, 31],
       [ 1,  2,  3, ..., 21, 31, 31],
       [ 1,  2,  3, ..., 21, 32, 31]], dtype=int64)

In [40]:
simil = np.array(
[
    [ # row 0
        [ # col 0
            0, 5, 5
        ],
        [ # col 1
            0, 5, 5
        ]
    ],
    [ # row 1
        [ # col 0
            5, 0, 5
        ],
        [ # col 1
            5, 5, 0
        ]
    ]
])

In [43]:
simil

array([[[0, 5, 5],
        [0, 5, 5]],

       [[5, 0, 5],
        [5, 5, 0]]])

In [45]:
# nakon argmin treba se dobiti array:
# [[0, 0],
#  [1, 2]]

simil_argmin = np.argmin(simil, axis=2)
simil_argmin

array([[0, 0],
       [1, 2]], dtype=int64)